### ISSUE TITLE
requests is missing from dependencies

### ISSUE THREAD

**Issue by lordi** [top-on/optimal-congress#5]
Installing `optimal-congress` in an empty Python 3.11 conda environment results in an `ImportError` for `requests` when running it.

**Comment by top-on** [comment]
thanks for reporting this @lordi !
the issue should be fixed with [release 0.7.2](https://github.com/top-on/optimal-congress/releases/tag/0.7.2).
would you be so kind and verity if dependency resolution in conda works, now?

**Comment by lordi** [comment]
Works fine now!
