### ISSUE TITLE
[Feature request] Exclude talks in a specific language

### ISSUE THREAD

**Issue by ghost** [top-on/optimal-congress#9]
Hi,

Since I (sadly) do not speak German, I am not going to listen to any talk in German. Instead of manually rating all these talks with a 0, it would be easier to have a filter based on language.
Thanks!

**Comment by top-on** [comment]
@restuccia , thanks for you interest in the tool.

i have just released [version 1.1.0](https://github.com/top-on/optimal-congress/releases/tag/1.1.0) with the option to set `optimal-congress rate --language en` (or `de` for that matter).

please let me know if that filter also works on your machine.

**Comment by ghost** [comment]
amazing, thank you very much <3

**Comment by ghost** [comment]
`--language` works on my machines (Fedora 41 and macOS Sonoma)
